version: "3.7"
services:
  frigate:
    container_name: frigate
    privileged: true
    restart: unless-stopped
    image: ghcr.io/blakeblackshear/frigate:stable-tensorrt
    shm_size: "2048mb" # update for your cameras based on calculation above
    group_add:
      - video 
    volumes:
      - /var/lib/docker/trt-models:/trt-models
      - /etc/localtime:/etc/localtime
      - ./config/config.yml:/config/config.yml
      - type: tmpfs # Optional: 1GB of memory, reduces SSD/SD Card wear
        target: /tmp/cache
        tmpfs:
          size: 2000000000
    network_mode: host
    runtime: nvidia
    environment:
      FRIGATE_RTSP_PASSWORD: "admin"
  node-exporter:
    restart: always
    privileged: true
    image: prom/node-exporter:latest
    container_name: node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - 9100:9100
    environment:
      - TZ=America/Monterrey

volumes:
  frigate_data:
    driver: local

