mqtt:
  host: 10.0.1.220
  port: 1883

cameras:
  # Define at least one camer
  patio:
    ffmpeg:
      inputs:
        - path: rtsp://admin:12345@10.0.1.202:8554/profile0?video&audio=aac&proto=Onvif
          roles:
            - detect
            - record
  rafael:
    ffmpeg:
      inputs:
        - path: rtsp://admin:12345@10.0.1.200:8554/profile0?video&audio=aac&proto=Onvif
          roles:
            - detect
            - record

  alberca:
    ffmpeg:
      inputs:
        - path: rtsp://admin:a1234567@192.168.1.6:554/Streaming/Channels/701?video&audio=aac&proto=Onvif
          roles:
            - detect
            - record
  palapa:
    ffmpeg:
      inputs:
        - path: rtsp://admin:a1234567@192.168.1.6:554/Streaming/Channels/301
          roles:
            - detect
            - record
  club:
    ffmpeg:
      inputs:
        - path: rtsp://admin:a1234567@192.168.1.6:554/Streaming/Channels/201
          roles:
            - detect
            - record

  vasarely:
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-copy
      inputs:
        - path: rtsp://127.0.0.1:8554/vasarely
          input_args: preset-rtsp-restream
          roles:
            - record
        - path: rtsp://127.0.0.1:8554/vasarely_sub
          input_args: preset-rtsp-restream
          roles:
            - detect
    live:
      stream_name: vasarely

go2rtc:
  streams:
    vasarely:
      - rtsp://admin:888888@10.0.1.201:8554/profile0?video&audio=aac&proto=Onvif
    vasarely_sub:
      - rtsp://admin:888888@10.0.1.201:8554/profile1?video&audio=aac&proto=Onvif
logger:
  # Optional: default log level (default: shown below)
  default: info
detect:
  enabled: false
  width: 1280
  height: 720
  fps: 3
objects:
  track:
    - person
    - car
    - motorcycle

birdseye:
  enabled: True
  mode: motion
  width: 1920
  height: 1080
  quality: 1
record:
  enabled: True
  retain:
    days: 5
    mode: all
  events:
    pre_capture: 5
    post_capture: 5

